# Generated by Django 4.0.3 on 2022-10-31 20:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='lk_clubs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
